# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator

class Add_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.setFixedSize(260, 290)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-4, -8, 271, 341))
        self.label.setStyleSheet("QLabel{\n"
"color: black;\n"
"                       background-color:rgb(200, 200, 200);   \n"
"border-radius:5px;                     /* <----  20px  */ \n"
"}\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(84, 260, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 10px;                     /* <----  20px  */ \n"
"border: 2px solid #094065;\n"
"                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/login_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setValidator(QRegExpValidator(QRegExp("[^!@#$%^&*_=-+(),.?\":{}|<>0-9]*"), self.lineEdit_1))
        
        self.lineEdit_1.setGeometry(QtCore.QRect(10, 30, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setStyleSheet("\n"
"QLineEdit {\n"
"color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"}\n"
"")
        self.lineEdit_1.setText("")
        self.lineEdit_1.setFrame(True)
        self.lineEdit_1.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_1.setDragEnabled(False)
        self.lineEdit_1.setReadOnly(False)
        self.lineEdit_1.setPlaceholderText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setValidator(QRegExpValidator(QRegExp("[^a-zA-Zа-яА-Я!@#$%^&*()?,\":{}|<>]*-=_+"), self.lineEdit_2))
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 90, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("\n"
"QLineEdit {\n"
"color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"}\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setValidator(QRegExpValidator(QRegExp("[^a-zA-Zа-яА-Я!@#$%^&*,()?\":{}|<>]*-=_+"), self.lineEdit_3))
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 150, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("\n"
"QLineEdit {\n"
"color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"}\n"
"")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(True)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setDragEnabled(False)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setPlaceholderText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 130, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(10, 210, 231, 31))
        self.comboBox.setStyleSheet("\n"
"color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление товара"))
        self.pushButton.setText(_translate("Form", "Добавить"))
        self.label_4.setText(_translate("Form", "Наименование товара :"))
        self.label_5.setText(_translate("Form", "Цена (в бел.рублях) :"))
        self.label_6.setText(_translate("Form", "Количество :"))
        self.label_7.setText(_translate("Form", "Еденица измерения :"))
        self.comboBox.setItemText(0, _translate("Form", "кг."))
        self.comboBox.setItemText(1, _translate("Form", "г."))
        self.comboBox.setItemText(2, _translate("Form", "л."))
        self.comboBox.setItemText(3, _translate("Form", "мл."))
        self.comboBox.setItemText(4, _translate("Form", "шт."))
