# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'The_Bazaar_Box.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QTableView, QHeaderView
from PyQt5.QtCore import QRegExp
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtCore import QLocale

class Ui_App(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(1080, 513)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 181, 521))
        self.locale = QLocale(QLocale.English, QLocale.UnitedStates)
        QLocale.setDefault(self.locale)
        self.label.setStyleSheet("QLabel{\n"
"color: black;\n"
"                       background-color:rgb(109, 126, 120);\n"
"\n"
"   \n"
"border-radius: 0px;                     /* <----  20px  */ \n"
"border: 1px solid #094065;\n"
"}\n"
"")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(Form)
        
        self.tableView.setGeometry(QtCore.QRect(180, 50, 901, 433))
        self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableView.setStyleSheet("QTableView{\n"
"color: black;\n"
"                       background-color: rgb(176, 176, 176);\n"
"\n"
"   \n"
"border-radius: 0px;                     /* <----  20px  */ \n"
"border: 1px solid #094065;\n"
"}\n"
"")
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 20, 141, 31))
        self.pushButton.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(200,200,200);   \n"
"border-radius: 5px;                     /* <----  20px  */ \n"
"border: 2px solid #094065;\n"
"text-align : left;\n"
"                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/storage_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 60, 141, 31))
        self.pushButton_2.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(200,200,200);   \n"
"border-radius: 5px;                     /* <----  20px  */ \n"
"border: 2px solid #094065;\n"
"text-align : left;                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/point_of_sale_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 100, 141, 31))
        self.pushButton_3.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(200,200,200);   \n"
"border-radius: 5px;                     /* <----  20px  */ \n"
"border: 2px solid #094065;\n"
"text-align : left;                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icons/monitoring_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
       
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(629, 482, 451, 31))
        self.pushButton_5.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(200,200,200);   \n"
"                  /* <----  20px  */ \n"
"                /* <----  20px  */ \n"
"border: 1px solid #094065;\n"
"text-align : center;                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("./icons/add_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 482, 451, 31))
        self.pushButton_6.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(200,200,200);   \n"
"                  /* <----  20px  */ \n"
"                /* <----  20px  */ \n"
"border: 1px solid #094065;\n"
"text-align : center;                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./icons/shopping_bag_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(190, 20, 211, 20))
        self.lineEdit.setValidator(QRegExpValidator(QRegExp("^[^!@#$%^&*_=-+(),.?\":{}|<>0-9]*$")))
        self.lineEdit.setStyleSheet("\n"
"QLineEdit {\n"
"color: black;\n"
"                       background-color:rgb(200, 200, 200);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(176, -1, 911, 51))
        self.label_3.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(190, 0, 141, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(450, 0, 161, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(450, 20, 211, 20))
        self.lineEdit_2.setValidator(QRegExpValidator(QRegExp("^[0-9.]*$")))
        self.lineEdit_2.setStyleSheet("\n"
"QLineEdit {\n"
"color: black;\n"
"                       background-color:rgb(200, 200, 200);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 480, 131, 31))
        self.label_6.setObjectName("label_6")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(710, 20, 131, 21))
        self.pushButton_10.setStyleSheet("\n"
"QPushButton {\n"
"color: black;\n"
"                       background-color:rgb(200, 200, 200);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("./icons/update_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon7)
        self.pushButton_10.setObjectName("pushButton_10")
        self.tableView.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
       
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.label_4.raise_()
        
        self.label_5.raise_()
        self.lineEdit_2.raise_()
        
        self.label_6.raise_()
        self.pushButton_10.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "The Bazaar Box"))
        self.pushButton.setText(_translate("Form", "Склад товаров"))
        self.pushButton_2.setText(_translate("Form", "Продажи"))
        self.pushButton_3.setText(_translate("Form", "График продаж"))
        
        self.pushButton_5.setText(_translate("Form", "Добавить товар"))
        self.pushButton_6.setText(_translate("Form", "Продать товар"))
        self.label_4.setText(_translate("Form", "Поиск товара по имени:"))
        self.label_5.setText(_translate("Form", "Поиск товара по количеству:"))
        self.label_6.setText(_translate("Form", "© 2023 [The BAzzAR Box]"))
        self.pushButton_10.setText(_translate("Form", "Обновить страницу"))
