# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QLocale
class Ui_Buy(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setFixedSize(471, 447)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 471, 451))
        self.label.setStyleSheet("QLabel{\n"
"color: black;\n"
"                       background-color:rgb(200, 200, 200);   \n"
"border-radius:5px;                     /* <----  20px  */ \n"
"}\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(30, 40, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("\n"
"color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.tableView = QtWidgets.QTableView(Form)
        self.tableView.setGeometry(QtCore.QRect(30, 100, 411, 221))
        self.tableView.setStyleSheet("color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;")
        self.tableView.setObjectName("tableView")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 330, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 350, 131, 31))
        self.lineEdit_2.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("\n"
"QLineEdit {\n"
"color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"}\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setPlaceholderText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 400, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                     /* <----  20px  */ \n"
"border: 2px solid #094065;\n"
"                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/point_of_sale_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(280, 20, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.spinBox = QtWidgets.QDoubleSpinBox(Form)
        self.spinBox.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.spinBox.setGeometry(QtCore.QRect(280, 40, 71, 31))
        self.spinBox.setSingleStep(0.1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("\n"
"color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                    \n"
"border: 2px solid #094065;\n"
"")
        self.spinBox.setObjectName("spinBox")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(312, 400, 131, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                     /* <----  20px  */ \n"
"border: 2px solid #094065;\n"
"                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/delete_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 40, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{color: black;\n"
"                       background-color:rgb(240,240,240);   \n"
"border-radius: 5px;                     /* <----  20px  */ \n"
"border: 2px solid #094065;\n"
"                                      \n"
"}\n"
"QPushButton:hover {\n"
" background:rgb(202, 219, 255);\n"
"transition: 1s;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icons/add_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "Выберите товар :"))
        self.label_5.setText(_translate("Form", "Текущий(е) товар(ы) :"))
        self.label_6.setText(_translate("Form", "Общая сумма чека :"))
        self.pushButton.setText(_translate("Form", "Продать"))
        self.label_7.setText(_translate("Form", "Количество :"))
        self.pushButton_3.setText(_translate("Form", "Удалить товар из чека"))
        self.pushButton_2.setText(_translate("Form", "Добавить"))
