# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QRegExpValidator
from PyQt5.QtCore import QRegExp

class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.setFixedSize(730, 560)
        self.label = QtWidgets.QLabel(Registration)
        self.label.setGeometry(QtCore.QRect(0, 0, 730, 560))
        self.label.setText("")
        self.label.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(12, 45, 36, 255), stop:1 rgba(239, 239, 237, 255))")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Registration)
        self.label_3.setGeometry(QtCore.QRect(330, 150, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Registration)
        self.label_2.setGeometry(QtCore.QRect(220, 135, 301, 290))
        self.label_2.setMinimumSize(QtCore.QSize(301, 0))
        self.label_2.setStyleSheet("QLabel{\n"
                                   "color: black;\n"
                                   "                       background-color:rgb(240, 240, 240);   \n"
                                   "border-radius: 40px;                     /* <----  20px  */ \n"
                                   "border: 2px solid #094065;\n"
                                   "}\n"
                                   "\n"
                                   "")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(
            ""))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Registration)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 210, 91, 31))
        self.lineEdit_2.setValidator(QRegExpValidator(QRegExp("[a-zA-Zа-яА-Я]+")))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("\n"
                                      "QLineEdit {\n"
                                      "color: black;\n"
                                      "                       background-color:rgb(200, 200, 200);   \n"
                                      "border-radius: 5px;                    \n"
                                      "border: 2px solid #094065;\n"
                                      "}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Registration)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 260, 161, 31))
        self.lineEdit_3.setValidator(QRegExpValidator(QRegExp(r"^[a-zA-Z0-9][a-zA-Z0-9_.-]*[^\W.]$")))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit_3.setMouseTracking(False)
        self.lineEdit_3.setStyleSheet("\n"
                                      "QLineEdit {\n"
                                      "color: black;\n"
                                      "                       background-color:rgb(200, 200, 200);   \n"
                                      "border-radius: 5px;                    \n"
                                      "border: 2px solid #094065;\n"
                                      "}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Registration)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 300, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("\n"
                                      "QLineEdit {\n"
                                      "color: black;\n"
                                      "                       background-color:rgb(200, 200, 200);   \n"
                                      "border-radius: 5px;                    \n"
                                      "border: 2px solid #094065;\n"
                                      "}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setFrame(True)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setDragEnabled(False)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton_4 = QtWidgets.QPushButton(Registration)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 300, 31, 31))
        self.pushButton_4.setStyleSheet("\n"
                                        "QPushButton {\n"
                                        "color: black;\n"
                                        "                       background-color:rgb(200, 200, 200);   \n"
                                        "border-radius: 5px;                    \n"
                                        "border: 2px solid #094065;\n"
                                        "}")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "./icons/password_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(Registration)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 260, 31, 31))
        self.pushButton_3.setStyleSheet("\n"
                                        "QPushButton {\n"
                                        "color: black;\n"
                                        "                       background-color:rgb(200, 200, 200);   \n"
                                        "border-radius: 5px;                    \n"
                                        "border: 2px solid #094065;\n"
                                        "}")
        self.pushButton_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "./icons/person_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(Registration)
        self.lineEdit_5.setGeometry(QtCore.QRect(380, 210, 91, 31))
        self.lineEdit_5.setValidator(QRegExpValidator(QRegExp("[a-zA-Zа-яА-Я]+")))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("\n"
                                      "QLineEdit {\n"
                                      "color: black;\n"
                                      "                       background-color:rgb(200, 200, 200);   \n"
                                      "border-radius: 5px;                    \n"
                                      "border: 2px solid #094065;\n"
                                      "}")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setFrame(True)
        self.lineEdit_5.setDragEnabled(False)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.radioButton = QtWidgets.QRadioButton(Registration)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(320, 340, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setTabletTracking(False)
        self.radioButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton.setAcceptDrops(False)
        self.radioButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            "./icons/visibility_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton.setIcon(icon2)
        self.radioButton.setChecked(False)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.pushButton = QtWidgets.QPushButton(Registration)
        self.pushButton.setGeometry(QtCore.QRect(330, 375, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{color: black;\n"
                                      "                       background-color:rgb(200,200,200);   \n"
                                      "border-radius: 10px;                     /* <----  20px  */ \n"
                                      "border: 2px solid #094065;\n"
                                      "                                      \n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      " background:rgb(202, 219, 255);\n"
                                      "transition: 1s;\n"
                                      "}\n"
                                      "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(
            "D:/pythonProject/PetProject/MyApp/icons/login_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.pushButton_4.raise_()
        self.pushButton_3.raise_()
        self.lineEdit_5.raise_()
        self.radioButton.raise_()
        self.pushButton.raise_()
       

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "The Bazaar Box"))
        self.label_3.setText(_translate("Registration", "SIGN UP"))
        self.lineEdit_2.setPlaceholderText(
            _translate("Registration", "Имя"))
        self.lineEdit_3.setPlaceholderText(_translate("Registration", "Логин"))
        self.lineEdit_4.setPlaceholderText(
            _translate("Registration", "Пароль"))
        self.lineEdit_5.setPlaceholderText(
            _translate("Registration", "Фамилия"))
        self.radioButton.setText(_translate("Registration", "Показать пароль"))
        self.pushButton.setText(_translate("Registration", "Регистрация"))
        
