# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import res_rs_rc
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Sign(object):
    def setupUi(self, Form):
        Form.setObjectName("Name")
        Form.setFixedSize(730, 560)
        Form.setWindowTitle("The Bazaar Box")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 730, 560))
        self.label_2.setMouseTracking(True)
        self.label_2.setStyleSheet("background:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(12, 45, 36, 255), stop:1 rgba(239, 239, 237, 255))")
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        
        self.label_2.setWordWrap(False)
        self.label_2.setOpenExternalLinks(False)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(215, 140, 301, 281))
        self.label.setMinimumSize(QtCore.QSize(301, 0))
        self.label.setStyleSheet("QLabel{\n"
                                 "color: black;\n"
                                 "                       background-color:rgb(240, 240, 240);   \n"
                                 "border-radius: 40px;                     /* <----  20px  */ \n"
                                 "border: 2px solid #094065;\n"
                                 "}\n"
                                 "\n"
                                 "")

        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(""))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(370, 340, 100, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{color: black;\n"
                                        "                       background-color:rgb(200,200,200);   \n"
                                        "border-radius: 10px;                     /* <----  20px  */ \n"
                                        "border: 2px solid #094065;\n"
                                        "                                      \n"
                                        "}\n"
                                        "QPushButton:hover {\n"
                                        " background:rgb(202, 219, 255);\n"
                                        "transition: 1s;\n"
                                        "}\n"
                                        "")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "./icons/how_to_reg_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(270, 340, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{color: black;\n"
                                      "                       background-color:rgb(200,200,200);   \n"
                                      "border-radius: 10px;                     /* <----  20px  */ \n"
                                      "border: 2px solid #094065;\n"
                                      "                                      \n"
                                      "}\n"
                                      "QPushButton:hover {\n"
                                      " background:rgb(202, 219, 255);\n"
                                      "transition: 1s;\n"
                                      "}\n"
                                      "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "./icons/login_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(340, 160, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(Form)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(310, 310, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.radioButton.setFont(font)
        self.radioButton.setTabletTracking(False)
        self.radioButton.setAcceptDrops(False)
        self.radioButton.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(
            "./icons/visibility_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)

        self.radioButton.setIcon(icon2)
        self.radioButton.setChecked(False)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(310, 230, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setStyleSheet("\n"
                                    "QLineEdit {\n"
                                    "color: black;\n"
                                    "                       background-color:rgb(200, 200, 200);   \n"
                                    "border-radius: 5px;                    \n"
                                    "border: 2px solid #094065;\n"
                                    "}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 270, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("\n"
                                      "QLineEdit {\n"
                                      "color: black;\n"
                                      "                       background-color:rgb(200, 200, 200);   \n"
                                      "border-radius: 5px;                    \n"
                                      "border: 2px solid #094065;\n"
                                      "}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(True)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setDragEnabled(False)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 230, 31, 31))
        self.pushButton_3.setStyleSheet("\n"
                                        "QPushButton {\n"
                                        "color: black;\n"
                                        "                       background-color:rgb(200, 200, 200);   \n"
                                        "border-radius: 5px;                    \n"
                                        "border: 2px solid #094065;\n"
                                        "}")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(
            "./icons/person_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(270, 270, 31, 31))
        self.pushButton_4.setStyleSheet("\n"
                                        "QPushButton {\n"
                                        "color: black;\n"
                                        "                       background-color:rgb(200, 200, 200);   \n"
                                        "border-radius: 5px;                    \n"
                                        "border: 2px solid #094065;\n"
                                        "}")
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(
            "./icons/password_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_2.raise_()
        self.label_3.raise_()
        self.lineEdit.raise_()
        self.radioButton.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "The Bazaar Box"))
        self.pushButton_2.setText(_translate("Form", "Регистрация"))
        self.pushButton.setText(_translate("Form", "Войти"))
        self.label_3.setText(_translate("Form", "LOGIN"))
        self.radioButton.setText(_translate("Form", "Показать пароль"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Логин"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Пароль"))
